export const CONNECT_SOCKET = {
	START: 'CONNECT_SOCKET_START',
	SUCCESS: 'CONNECT_SOCKET_SUCCESS',
	ERROR: 'CONNECT_SOCKET_ERROR',
};

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const MESSAGE_ERROR = 'MESSAGE_ERROR';
