export const CONNECT_SOCKET = 'CONNECT_SOCKET';
export const CONNECT_SOCKET_SUCCESS = 'CONNECT_SOCKET_SUCCESS';
export const CONNECT_SOCKET_ERROR = 'CONNECT_SOCKET_ERROR';

export const SEND_MESSAGE = 'SEND_MESSAGE';
